### ISSUE TITLE
Add terraform-docs inputs and outputs for all Terraform modules

### ISSUE THREAD

**Issue by guangie88** [GovTechSG/terraform-modules#107]
Use [`terraform-docs`](https://github.com/segmentio/terraform-docs) to standardize all input and output descriptions for all Terraform modules.

Command to use is `terraform-docs md .`

**Comment by sulaiman-alwie** [comment]
Please see PR https://github.com/GovTechSG/terraform-modules/pull/142

**Comment by lawliet89** [comment]
Fixed.
